stages:
  - build
  - test
  - package

job_build:
  stage: build
  script:
    - ./cicd/build.sh
  artifacts:
    paths:
      - src/app

job_test:
  stage: test
  script:
    - ./cicd/test.sh

job_package:
  stage: package
  script:
    - ./cicd/package.sh
  artifacts:
    paths:
      - "*.deb"
