name: Deploy to Docker Hub

on:
  push:
    branches: [ main, master ]

jobs:
  full_pipeline:
    runs-on: self-hosted  # виртуалка

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Test
        run: |
          chmod +x cicd/build.sh
          chmod +x cicd/test.sh
          ./cicd/build.sh
          ./cicd/test.sh

      - name: Build Package
        run: |
          chmod +x cicd/package.sh
          ./cicd/package.sh

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          # Имя образа: логин/название_лабы:версия
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lab3-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lab3-app:latest
